# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = '2'

Vagrant.require_version '>= 1.4.3'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

    config.vm.define 'ubuntu-13.10-x86_64-puppet' do |machine|
        machine.vm.box = 'ubuntu-13.10-x86_64'
    end

    config.vm.synced_folder '../config', '/config'

    config.vm.provider :virtualbox do |vb, override|
        vb.gui              = false
        vb.name             = "#{config.vm.box}-puppet"
        override.vm.box_url = '../../../boxes/virtualbox/ubuntu-13.10-x86_64.box'
    end

    config.vm.provider :vmware_fusion do |vf, override|
        vf.gui              = false
        vf.name             = "#{config.vm.box}-puppet"
        override.vm.box_url = '../../../boxes/vmware/ubuntu-13.10-x86_64.box'
    end

    config.librarian_puppet.puppetfile_dir = '../config'

    config.librarian_puppet.placeholder_filename = 'empty.txt'

    config.vm.provision :puppet do |puppet|
        puppet.manifests_path = '../config/manifests'
        puppet.module_path    = '../config/site', '../config/modules'
        puppet.manifest_file  = 'site.pp'
    end

end
