# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = '2'

Vagrant.require_version '>= 1.4.3'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

    config.vm.define 'ubuntu-13.10-x86_64-chef' do |machine|
        machine.vm.box = 'ubuntu-13.10-x86_64'
    end

    config.vm.provider :virtualbox do |vb, override|
        vb.gui              = false
        vb.name             = "#{config.vm.box}-chef"
        override.vm.box_url = '../../../boxes/virtualbox/ubuntu-13.10-x86_64.box'
    end

    config.vm.provider :vmware_fusion do |vf, override|
        vf.gui              = false
        vf.name             = "#{config.vm.box}-chef"
        override.vm.box_url = '../../../boxes/vmware/ubuntu-13.10-x86_64.box'
    end

    config.vm.provision :chef_solo do |chef|
        chef.cookbooks_path = '../cookbooks'
        chef.roles_path     = '../roles'
        chef.data_bags_path = '../data_bags'
        #   chef.add_recipe "mysql"
        #   chef.add_role "web"
        #
        #   # You may also specify motd JSON attributes:
        #   chef.json = { :mysql_password => "foo" }
    end

end
