# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = '2'

Vagrant.require_version '>= 1.4.3'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

    config.vm.provider :virtualbox do |vb, override|
        vb.gui              = false
        vb.name             = "#{config.vm.box}-puppet"
        override.vm.box_url = '../boxes/virtualbox/centos-6.5-x86_64.box'
    end

    config.vm.provider :vmware_fusion do |vf, override|
        vf.gui              = false
        vf.name             = "#{config.vm.box}-puppet"
        override.vm.box_url = '../boxes/vmware/centos-6.5-x86_64.box'
    end

    config.vm.define 'centos-6.5-x86_64-puppet', primary: true do |machine|

        machine.librarian_puppet.puppetfile_dir       = '../config/puppet'
        machine.librarian_puppet.placeholder_filename = 'empty.txt'

        machine.vm.box = 'centos-6.5-x86_64'

        machine.vm.provision :puppet do |puppet|
            puppet.manifests_path = '../config/puppet/manifests'
            puppet.module_path    = %w(../config/puppet/site ../config/puppet/modules)
            puppet.manifest_file  = 'site.pp'
        end

    end

    config.vm.define 'centos-6.5-x86_64-chef' do |machine|

        machine.vm.box = 'centos-6.5-x86_64'

        machine.vm.provision :chef_solo do |chef|
            chef.cookbooks_path = '../config/chef/cookbooks'
            chef.roles_path     = '../config/chef/roles'
            chef.data_bags_path = '../config/chef/data_bags'
        end

    end

end
