# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

    config.vm.box     = "centos-6.5-x86_64"

    config.vm.provider :virtualbox do |vb, override|
        override.vm.box_url = "../../boxes/virtualbox/centos-6.5-x86_64.box"
    end

    config.vm.provider :vmware_fusion do |vm, override|
        override.vm.box_url = "../../boxes/vmware/centos-6.5-x86_64.box"
    end

end
